services:
  caddy:
    image: ghcr.io/baibusu-social/caddy:2.10.2
    container_name: mgmt_caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
volumes:
  caddy_data:
    driver: local
  caddy_config:
